version: "3.9"

services:
  autosugalaa-next:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ""
    image: autosugalaa-next:latest
    container_name: autosugalaa-next
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: 103.153.141.202
      DB_USER: root
      DB_PASSWORD: Test#123
      DB_NAME: autosugalaa
      DB_PORT: 3306
    ports:
      - "3000:3000"
